name: piplineworkflow

on:
 push:
   branches:
     - master
 pull_request:
   branches:
      - master

jobs:
  build:
    name: Azurepipelines
    runs-on: ubuntu-latest
    steps:
    - name: Azurepipelines
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/ravikotatechie/my-Agileproj/_git/gitapp
        azure-pipeline-name: 'gitapp02'
        azure-devops-token: ${{secrets.AZURE_DEVOPS_TOKEN}}
